// ============================================================================
// Judicial Streamlining Tool — Mock Data & Seed Constants
// ============================================================================
// This file contains ALL mock/seed data used across the application.
// Each section is tagged with a "TO-DO (BACKEND):" comment indicating
// where the real data will come from once the FastAPI backend is integrated.
// ============================================================================

import type {
  AgentKey,
  AgentArchetype,
  AgentDebateStyle,
  AgentNode,
  DebateScriptEntry,
  ConsensusEntry,
  BarEntry,
  AdvantageEntry,
  FlawEntry,
  VerdictData,
} from "@/lib/types"

// ── Agent Archetypes ────────────────────────────────────────────────────────
// TO-DO (BACKEND): These archetypes will be dynamically generated by the
// FastAPI `/api/v1/simulation/init` endpoint based on the selected
// jurisdiction and case profile. The backend returns a JSON array of
// archetype definitions. Replace this static array with the response
// from `POST /api/v1/simulation/init`.

export const AGENT_ARCHETYPES: AgentArchetype[] = [
  { id: "alpha", label: "Agent \u03B1", archetype: "Strict Constitutionalist", color: "#d97706" },
  { id: "beta",  label: "Agent \u03B2", archetype: "Pragmatist",              color: "#0ea5e9" },
  { id: "gamma", label: "Agent \u03B3", archetype: "Civil Libertarian",       color: "#10b981" },
  { id: "delta", label: "Agent \u03B4", archetype: "Judicial Minimalist",     color: "#a855f7" },
]

// ── Agent Debate Styles (UI-only) ──────────────────────────────────────────
// These map each agent key to Tailwind classes for the debate transcript.
// They stay on the frontend and are keyed off the agent IDs from the backend.

export const AGENT_DEBATE_STYLES: Record<AgentKey, AgentDebateStyle> = {
  alpha: { label: "Agent \u03B1", bgClass: "bg-amber-900/40 border-amber-700/40",   textColorClass: "text-amber-400"   },
  beta:  { label: "Agent \u03B2", bgClass: "bg-sky-900/40 border-sky-700/40",       textColorClass: "text-sky-400"     },
  gamma: { label: "Agent \u03B3", bgClass: "bg-emerald-900/40 border-emerald-700/40", textColorClass: "text-emerald-400" },
  delta: { label: "Agent \u03B4", bgClass: "bg-purple-900/40 border-purple-700/40", textColorClass: "text-purple-400"  },
}

// ── Swarm Arena Agent Nodes ────────────────────────────────────────────────
// TO-DO (BACKEND): Node positions and count will be returned by the
// simulation init endpoint. The (x, y) positions here are normalized 0..1
// and translated to pixel coordinates at render time.

export const AGENT_NODES: AgentNode[] = [
  { id: "alpha", label: "Agent \u03B1", archetype: "Strict Constitutionalist", color: "#d97706", x: 0.2,  y: 0.22 },
  { id: "beta",  label: "Agent \u03B2", archetype: "Pragmatist",              color: "#0ea5e9", x: 0.8,  y: 0.22 },
  { id: "gamma", label: "Agent \u03B3", archetype: "Civil Libertarian",       color: "#10b981", x: 0.2,  y: 0.78 },
  { id: "delta", label: "Agent \u03B4", archetype: "Judicial Minimalist",     color: "#a855f7", x: 0.8,  y: 0.78 },
]

// ── Debate Transcript Script ───────────────────────────────────────────────
// TO-DO (BACKEND): Replace this static script with a WebSocket stream from
// `ws://<host>/api/v1/simulation/{sim_id}/debate`. Each message arrives as
// a JSON frame: { "agent": "alpha", "content": "..." , "turn": 1 }.
// The frontend should append each incoming frame to the debateTranscript
// state array in the useSimulation hook.

export const MOCK_DEBATE_SCRIPT: DebateScriptEntry[] = [
  { agent: "alpha", content: "The precedent in Marbury v. Madison is unambiguous here. The constitutional framework demands strict adherence to the separation of powers doctrine. Any deviation would undermine the structural integrity of the ruling." },
  { agent: "beta",  content: "With respect to Agent \u03B1, strict originalism ignores the practical realities. The demographic data from Cook County shows a 34% disparity in sentencing outcomes. We need a pragmatic approach that accounts for real-world impact." },
  { agent: "gamma", content: "Both positions miss the fundamental issue. The Fourth Amendment protections are not negotiable. The evidence obtained through the surveillance program should be excluded entirely under the fruit of the poisonous tree doctrine." },
  { agent: "delta", content: "I urge restraint. The court should rule as narrowly as possible. Addressing only the procedural question avoids setting an overbroad precedent that could have unintended consequences in future litigation." },
  { agent: "alpha", content: "Agent \u03B4\u2019s minimalism is intellectually consistent but practically untenable. The constitutional question is squarely before us. Ducking it would be a dereliction of judicial duty under Article III standing requirements." },
  { agent: "beta",  content: "Running the Monte Carlo simulation on sentencing outcomes: with a strict constitutionalist framework, we see a 2.3x increase in appellate reversals. The pragmatic cost-benefit analysis favors a broader ruling here." },
  { agent: "gamma", content: "I note that Agent \u03B2\u2019s utilitarian calculus assigns zero weight to individual liberty. The rights of the defendant are not a variable to be optimized. They are a floor, not a ceiling." },
  { agent: "delta", content: "Converging analysis: Agents \u03B1 and \u03B3 share a structural commitment to textual interpretation, though they diverge on scope. I propose we narrow the holding to the procedural due process claim and reserve the substantive question." },
  { agent: "alpha", content: "Unacceptable. The Necessary and Proper Clause gives Congress explicit authority here. The legislative history from 1789 to 2024 supports a robust reading of federal jurisdiction over interstate commerce implications of this case." },
  { agent: "beta",  content: "Swarm analysis indicates 67% convergence toward a moderate position. Demographic jury modeling shows this outcome polls at 78% acceptance across the simulated jurisdiction. Recommend we proceed with a balanced framework." },
  { agent: "gamma", content: "Polling data is irrelevant to constitutional adjudication. The Bill of Rights exists precisely to protect against majoritarian impulses. Agent \u03B2 conflates popularity with legitimacy." },
  { agent: "delta", content: "Final position: I concur with Agent \u03B3 on the exclusionary rule question but side with Agent \u03B2 on the remedial framework. A split holding serves judicial economy while preserving core protections." },
]

// ── Verdict Data ───────────────────────────────────────────────────────────
// TO-DO (BACKEND): The entire VerdictData object will be returned as a
// single JSON response from `POST /api/v1/simulation/{sim_id}/verdict`.
// The Arbiter LLM generates the summary, consensus scores, advantages,
// and flaws as structured JSON conforming to the VerdictData Pydantic model.
// Replace this mock with: const data = await fetch(`/api/v1/simulation/${simId}/verdict`).then(r => r.json())

export const MOCK_CONSENSUS: ConsensusEntry[] = [
  { name: "Agent \u03B2 \u2014 Pragmatist",        value: 42, color: "#0ea5e9" },
  { name: "Agent \u03B1 \u2014 Constitutionalist",  value: 28, color: "#d97706" },
  { name: "Agent \u03B3 \u2014 Civil Libertarian",   value: 18, color: "#10b981" },
  { name: "Agent \u03B4 \u2014 Minimalist",          value: 7,  color: "#a855f7" },
  { name: "Undecided",                               value: 5,  color: "#525252" },
]

export const MOCK_BAR_DATA: BarEntry[] = [
  { agent: "\u03B2 Pragmatist",        nodes: 42, fill: "#0ea5e9" },
  { agent: "\u03B1 Constitutionalist",  nodes: 28, fill: "#d97706" },
  { agent: "\u03B3 Libertarian",        nodes: 18, fill: "#10b981" },
  { agent: "\u03B4 Minimalist",         nodes: 7,  fill: "#a855f7" },
  { agent: "Undecided",                 nodes: 5,  fill: "#525252" },
]

export const MOCK_ADVANTAGES: AdvantageEntry[] = [
  { id: 1, argument: "Precedent alignment with Richardson v. State (2019)",                        weight: 94.2, agent: "Agent \u03B2", category: "Legal Precedent" },
  { id: 2, argument: "Demonstrated economic impact analysis sustained under cross-examination",    weight: 91.7, agent: "Agent \u03B2", category: "Evidentiary"     },
  { id: 3, argument: "Jurisdictional statute \u00A7 4-212(b) supports proportionality standard",   weight: 88.4, agent: "Agent \u03B1", category: "Statutory"       },
  { id: 4, argument: "Swarm convergence on due process framework exceeded 78% threshold",          weight: 86.1, agent: "Agent \u03B2", category: "Consensus"       },
  { id: 5, argument: "Witness testimony corroboration index: 0.89 (high confidence)",              weight: 83.5, agent: "Agent \u03B3", category: "Evidentiary"     },
]

export const MOCK_FLAWS: FlawEntry[] = [
  { id: 1, flaw: "Circular reasoning detected in strict originalist interpretation of Amendment IV applicability",  severity: "Critical", agent: "Agent \u03B1", penalty: -12.4 },
  { id: 2, flaw: "Failure to account for jurisdictional variance in Cook County sentencing guidelines",             severity: "Major",    agent: "Agent \u03B4", penalty: -9.8  },
  { id: 3, flaw: "Straw man fallacy in rebuttal to proportionality argument (Turn 7, \u00A73.2)",                   severity: "Major",    agent: "Agent \u03B1", penalty: -8.3  },
  { id: 4, flaw: "Insufficient empirical grounding for recidivism rate projections",                                severity: "Moderate", agent: "Agent \u03B3", penalty: -5.1  },
  { id: 5, flaw: "Appeal to authority without citation verification in deliberation round 4",                       severity: "Minor",    agent: "Agent \u03B4", penalty: -2.7  },
]

export const MOCK_SUMMARY_TEXT = `Following a 12-round multi-agent adversarial deliberation across four archetypal judicial reasoning frameworks, the simulation concludes that the Pragmatist stance (Agent \u03B2) holds the strongest composite merit score of 0.871 \u00B1 0.023.

The central dispute revolved around the applicability of proportionality standards under jurisdictional statute \u00A7 4-212(b) within the Cook County, IL framework. Agent \u03B2\u2019s argumentation demonstrated superior precedent alignment, surviving rigorous cross-examination from the Strict Constitutionalist (Agent \u03B1) and the Civil Libertarian (Agent \u03B3) archetypes.

Key inflection points occurred during Rounds 4 and 9, where Agent \u03B1\u2019s originalist framework was challenged on circular reasoning grounds, causing a measurable 14.2% swarm migration toward Agent \u03B2\u2019s position. The Judicial Minimalist (Agent \u03B4) maintained a narrow deferential posture but failed to address jurisdictional variance in sentencing guidelines, resulting in progressive node attrition throughout the simulation.

The final demographic jury swarm distribution settled at 42% Pragmatist, 28% Constitutionalist, 18% Civil Libertarian, 7% Minimalist, with 5% remaining undecided\u2014indicating a clear but non-unanimous directional consensus. Geographic bias correction was applied throughout. The Arbiter recommends this synthesis as a decision-support input only; final judicial authority rests with the presiding officer.`

/** Assembled mock verdict for use in development. */
export function getMockVerdictData(): VerdictData {
  return {
    simulationId: "SIM-2026-00417",
    jurisdiction: "Cook County, IL",
    depthLabel: "DEEP DELIBERATION",
    timestamp: new Intl.DateTimeFormat("en-US", {
      dateStyle: "full",
      timeStyle: "medium",
    }).format(new Date()),
    consensus: MOCK_CONSENSUS,
    barData: MOCK_BAR_DATA,
    advantages: MOCK_ADVANTAGES,
    flaws: MOCK_FLAWS,
    summaryText: MOCK_SUMMARY_TEXT,
    compositeMerit: "0.871 \u00B1 0.023",
    confidence: "HIGH",
    deliberationRounds: 12,
  }
}
